### ISSUE TITLE
Ruby Rails Mimemagic Breaks stable/11 build

### ISSUE THREAD

**Issue by kthecoder** [madewhatnow/OpenProjectRaspberryPi#11]
[Article](https://dev.to/cseeman/what-s-up-with-mimemagic-breaking-everything-he1)

Ruby Rails apparently has a major breaking change that destroys the ability to build stable/11.

I tried following your instructions to install on RPI4 and I ran into the issue of the latest breaking change to Ruby Rails. So I swapped stable/11 for release/11.2 and I followed all the way through the guide.

But all I get is the Apache2 Debian Default Page. I have no clue how to even look for errors to begin to find a way to get 11.2 to work. Unsure why apache2's sites-available isn't using the openproject spec.

I will try to use the image file instead.

**Comment by madewhatnow** [comment]
> 
> 
> [Article](https://dev.to/cseeman/what-s-up-with-mimemagic-breaking-everything-he1)
> 
> Ruby Rails apparently has a major breaking change that destroys the ability to build stable/11.
> 
> I tried following your instructions to install on RPI4 and I ran into the issue of the latest breaking change to Ruby Rails. So I swapped stable/11 for release/11.2 and I followed all the way through the guide.
> 
> But all I get is the Apache2 Debian Default Page. I have no clue how to even look for errors to begin to find a way to get 11.2 to work. Unsure why apache2's sites-available isn't using the openproject spec.
> 
> I will try to use the image file instead.

Did the image work out for you? I'll give this a few days and then try to run through the installation process again with the updated version.

**Comment by kthecoder** [comment]
Yes the image worked. Thank you. If you get a newer version to work let me know.
