### ISSUE TITLE
Export WP overview as PDF

### ISSUE THREAD

**Issue by MatteoN82** [madewhatnow/OpenProjectRaspberryPi#8]
Hi. I am having trouble in exporting the structure of my WPs from OpenProject. I get to the "The export is being prepared and will be downloaded shortly." message, but then nothing happens, no matter how long I wait.

Have you experienced this as well?

Thanks.
Best.

**Comment by madewhatnow** [comment]
I'm looking into it - do you get any error messages in the log files?

**Comment by madewhatnow** [comment]
Appears to work in release 11.
